project_id = "sfdarjnmvdnwqcnbwqdo"

[functions.heartbridge-chat]
verify_jwt = false

[functions.heartbridge-upload-knowledge]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false


[functions.process-csv]
verify_jwt = false

[functions.process-document]
verify_jwt = false

[functions.rag-chat]
verify_jwt = false

[functions.analyze-knowledge]
verify_jwt = false
